// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViettalAPI.Data;

#nullable disable

namespace ViettalAPI.Migrations
{
    [DbContext(typeof(ViettalDbContext))]
    [Migration("20260615134745_Init database")]
    partial class Initdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ViettalAPI.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user-customer",
                            Email = "customer@simdep.vn",
                            FullName = "Nguyễn Văn Khách",
                            Password = "$2a$11$.TWYGrbFs7kG64fcbVW/oOxyWwMk3IyuCY91EaWLXTPeiMASS7cRu",
                            Phone = "0909000000",
                            Role = "Customer"
                        },
                        new
                        {
                            Id = "user-admin",
                            Email = "admin@simdep.vn",
                            FullName = "Quản trị viên",
                            Password = "$2a$11$vWiZj4kZj7CkpUvV/aonDuJAnDd1p/N5k4ydIi3J4MFpbElYTbXM6",
                            Phone = "0909999999",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("ViettalAPI.Models.BeautifulSim", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sims");

                    b.HasData(
                        new
                        {
                            Id = "sim-001",
                            Carrier = "Mobifone",
                            Description = "Số dễ nhớ, phù hợp kinh doanh và xây dựng thương hiệu cá nhân.",
                            Meaning = "Dãy 8 tượng trưng cho phát tài, phát lộc.",
                            PhoneNumber = "0909 888 888",
                            Price = 125000000,
                            Status = "Available",
                            Type = "Sim lục quý"
                        },
                        new
                        {
                            Id = "sim-002",
                            Carrier = "Viettel",
                            Description = "Cân bằng giữa độ đẹp, ngân sách và tính dễ đọc.",
                            Meaning = "Cặp 68 và 86 mang ý nghĩa lộc phát luân chuyển.",
                            PhoneNumber = "0986 686 868",
                            Price = 28500000,
                            Status = "Available",
                            Type = "Sim lộc phát"
                        },
                        new
                        {
                            Id = "sim-003",
                            Carrier = "Vinaphone",
                            Description = "Phù hợp chủ shop, tư vấn viên và người làm dịch vụ cần số dễ nhớ.",
                            Meaning = "Tam hoa 3 tạo cảm giác chắc chắn, bền vững.",
                            PhoneNumber = "0912 333 333",
                            Price = 42000000,
                            Status = "Available",
                            Type = "Sim tam hoa"
                        },
                        new
                        {
                            Id = "sim-004",
                            Carrier = "Vietnamobile",
                            Description = "Một lựa chọn cá nhân hóa, dễ nhớ khi giới thiệu.",
                            Meaning = "Gắn với năm sinh 1999, dễ tạo dấu ấn cá nhân.",
                            PhoneNumber = "0888 197 1999",
                            Price = 9600000,
                            Status = "Sold",
                            Type = "Sim năm sinh"
                        },
                        new
                        {
                            Id = "sim-005",
                            Carrier = "Viettel",
                            Description = "Phù hợp người kinh doanh cần số hotline nổi bật.",
                            Meaning = "Tứ quý 4 tạo nhịp số đều, chắc và rất dễ ghi nhớ.",
                            PhoneNumber = "0901 444 444",
                            Price = 65000000,
                            Status = "Available",
                            Type = "Sim tứ quý"
                        },
                        new
                        {
                            Id = "sim-006",
                            Carrier = "Mobifone",
                            Description = "Dãy số có nhịp đọc đẹp, giá vừa phải.",
                            Meaning = "Cặp 79 tượng trưng cho thần tài, may mắn trong công việc.",
                            PhoneNumber = "0937 797 979",
                            Price = 18500000,
                            Status = "Available",
                            Type = "Sim thần tài"
                        },
                        new
                        {
                            Id = "sim-007",
                            Carrier = "Gmobile",
                            Description = "Số đẹp cho nhu cầu cá nhân hoặc cửa hàng nhỏ.",
                            Meaning = "Cụm 555 lặp lại tạo cảm giác cân bằng và dễ nhớ.",
                            PhoneNumber = "0999 555 555",
                            Price = 32000000,
                            Status = "Sold",
                            Type = "Sim tam hoa"
                        },
                        new
                        {
                            Id = "sim-008",
                            Carrier = "Vinaphone",
                            Description = "Số có nhịp đọc mềm, dễ giới thiệu qua điện thoại.",
                            Meaning = "Cặp 168 gợi ý nghĩa sinh lộc phát.",
                            PhoneNumber = "0918 168 168",
                            Price = 22000000,
                            Status = "Available",
                            Type = "Sim lộc phát"
                        });
                });

            modelBuilder.Entity("ViettalAPI.Models.SimOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SimId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "ORD-1001",
                            Address = "Thành phố Hồ Chí Minh",
                            CreatedAt = new DateTime(2026, 6, 15, 9, 47, 41, 834, DateTimeKind.Utc).AddTicks(9772),
                            Note = "Giao hàng giờ hành chính",
                            ReceiverName = "Nguyễn Văn Khách",
                            ReceiverPhone = "0909000000",
                            SimId = "sim-002",
                            Status = "Pending",
                            TotalPrice = 28500000,
                            UserId = "user-customer"
                        },
                        new
                        {
                            Id = "ORD-1002",
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2026, 6, 13, 13, 47, 41, 834, DateTimeKind.Utc).AddTicks(9782),
                            Note = "",
                            ReceiverName = "Nguyễn Văn Khách",
                            ReceiverPhone = "0909000000",
                            SimId = "sim-004",
                            Status = "Completed",
                            TotalPrice = 9600000,
                            UserId = "user-customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
